server:
  port: 8761

spring:
  application:
    name: discovery-service


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
#      prometheus:

  endpoint:
 #   prometheus:

    health:
      show-details: always